# Site settings
title: Lyons in Beta
email: hello@davidlyons.net
description:
baseurl: ""
url: "http://lyonsinbeta.com"
twitter_username: lyonsinbeta
googleplus_username: DavidLyons
github_username:  lyonsinbeta

# Build settings
markdown: kramdown
permalink: pretty
