# Site settings
title: The Blog of David Lyons
email: hi@lyonsinbeta.com
description:
baseurl: ""
url: "http://lyonsinbeta.com"
twitter_username: lyonsinbeta
googleplus_username: DavidLyons
github_username:  lyonsinbeta

# Build settings
markdown: kramdown
permalink: pretty
